name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_install
        uses: asdf-vm/actions/setup@v3
      - name: asdf_plugin_add
        uses: asdf-vm/actions/plugins-add@v3
