name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup jq
        uses: vegardit/gha-setup-jq@v1
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          asdf_version: 0.16.7
          plugin: ideac
          command: ideac --version
